ASCAT to RaggedExperiment vignette
Bioconductor/RaggedExperiment pull request #28
Opened 2023-04-18 16:18 UTC by Lydia-King

2023-04-25 19:24 UTC, LiNk-NY requested changes
Please see the comments above.

2023-04-25 19:24 UTC, LiNk-NY commented on data/ASCAT_Sample_File.txt
This file should go `inst/extdata`

2023-04-25 19:24 UTC, LiNk-NY commented on vignettes/ASCAT_to_RaggedExperiment.Rmd
> +The [*RaggedExperiment*](https://bioconductor.org/packages/3.16/RaggedExperiment) package provides a flexible data representation for copy number, mutation and other ragged array schema for genomic l
The link could be `r Biocpkg('RaggedExperiment')` so that it is not tied to a package version (e.g., `3.16` here)

2023-04-25 19:24 UTC, LiNk-NY commented on vignettes/ASCAT_to_RaggedExperiment.Rmd
> +The [*RaggedExperiment*](https://bioconductor.org/packages/3.16/RaggedExperiment) package provides a flexible data representation for copy number, mutation and other ragged array schema for genomic l
Can you wrap the lines to 80 character limit? I like to use vim `gqq` .

2023-04-25 19:24 UTC, LiNk-NY commented on vignettes/ASCAT_to_RaggedExperiment.Rmd
> +ASCAT_data <- read.csv("../data/ASCAT_Sample_File.txt", sep="\t")
This should use `system.file` and the `extdata` location

2023-04-25 19:24 UTC, LiNk-NY commented on vignettes/ASCAT_to_RaggedExperiment.Rmd
> +## ASCAT to `GRanges` objects
Is it typical to get a single sample from a file? If not, it may be better to go straight into the `makeGRangesListFromDataFrame`

2023-04-25 19:24 UTC, LiNk-NY commented on vignettes/ASCAT_to_RaggedExperiment.Rmd
> +
I think for these examples, it is easier to just use `makeGRangesListFromDataFrame` unless there is a workflow (pipeline output) that provides multiple files where each file contains a single sample.

2023-04-25 19:24 UTC, LiNk-NY commented on vignettes/ASCAT_to_RaggedExperiment.Rmd
> +sample_list_GRanges_ex1 <- makeGRangesListFromDataFrame(ASCAT_data_1sample, ignore.strand=TRUE, seqnames.field=c("chr"), start.field="startpos", end.field=c("endpos"), keep.extra.columns=TRUE, split.
This is good. You can remove the `c` function if the string is a single scalar value, i.e., `identical(c("chr"), "chr")`

2023-04-25 19:24 UTC, LiNk-NY commented on vignettes/ASCAT_to_RaggedExperiment.Rmd
> +sample_list_GRanges_ex2 <- makeGRangesListFromDataFrame(ASCAT_data, ignore.strand=TRUE, seqnames.field=c("chr"), start.field="startpos", end.field=c("endpos"), keep.extra.columns=TRUE, split.field =
The code indentation should follow `RaggedExperiment.Rmd` which has multiples of 4 spaces and max 80 character width.

2023-04-25 19:24 UTC, LiNk-NY commented on vignettes/ASCAT_to_RaggedExperiment.Rmd
> +## ASCAT to `list` of `GRanges`
I don't know how common this is. It may be more typical to input each `GRanges` into the `GRangesList` constructor.

2023-04-25 19:24 UTC, LiNk-NY commented on vignettes/ASCAT_to_RaggedExperiment.Rmd
> +## Using a `List` of `GRanges` with metadata
Perhaps have a section that mentions what types of inputs are possible but it should not be a recurring topic in the vignette. I think it's best to highlight the typical workflow with the data outputs provided by ASCAT. You could even show an example (unevaluated) ASCAT command at the beginning of the vignette.

2023-04-25 19:24 UTC, LiNk-NY commented on vignettes/ASCAT_to_RaggedExperiment.Rmd
> +sample_list_GRanges_ex2 <- makeGRangesListFromDataFrame(ASCAT_data, ignore.strand=TRUE, seqnames.field=c("chr"), start.field="startpos", end.field=c("endpos"), keep.extra.columns=TRUE, split.field =
Perhaps take a look at the `styler` package

2023-05-03 18:01 UTC, Lydia-King commented
Made the suggested changes! Happy to make more changes/additions if you have any more feedback :)

2023-05-03 19:41 UTC, LiNk-NY requested changes
Thanks Lydia, this looks good. There are a few minor changes. 
Also, can you remove the `html` file? This is generated when the package is built.

2023-05-03 19:41 UTC, LiNk-NY commented on vignettes/ASCAT_to_RaggedExperiment.Rmd
> +```{r, message = FALSE, warning = FALSE, eval = F}
Use `FALSE` instead of `F`

2023-05-03 19:41 UTC, LiNk-NY commented on vignettes/ASCAT_to_RaggedExperiment.Rmd
> +ASCAT_data_S1 <- read.csv(
should this call be `read.table`?

2023-05-03 19:41 UTC, LiNk-NY commented on vignettes/ASCAT_to_RaggedExperiment.Rmd
> +    sep="\t"
same here

2023-05-03 22:28 UTC, LiNk-NY commented on vignettes/ASCAT_to_RaggedExperiment.Rmd
> +ASCAT_data_S1 <- read.csv(
Sorry I meant `read.delim` but I can take care of this.

2023-05-03 22:59 UTC, LiNk-NY commented
Thank you Lydia! You can see the commit here: 9809d38008ea2092845da72adc78bb595d806466
I've squashed them into one and I have added you to the `DESCRIPTION` file.

2023-05-03 22:59 UTC, closed without merging